#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l vmem=8gb
#PBS -l walltime=5:00:00

set -e
set -x

mkdir -p output
cp $(jq -r .bvecs config.json) output/dwi.bvecs
cp $(jq -r .bvals config.json) output/dwi.bvals
chmod -R +w output

RICIAN=$(jq -r .rician config.json)

if $RICIAN_OPT
then
    RICIAN_OPT="--rician"
else
    RICIAN_OPT=""
fi

time singularity exec -e docker://brainlife/dipy:1.1.1 dipy_denoise_nlmeans \
    --force \
    --out_dir output \
    --sigma $(jq -r .sigma config.json) \
    --patch_radius $(jq -r .patch_radius config.json) \
    --block_radius $(jq -r .block_radius config.json) \
    $RICIAN_OPT \
    --out_denoised dwi.nii.gz \
    $(jq -r .dwi config.json)

echo "done"
